// apps/web/src/components/board/BoardCardItem.vue
<script setup lang="ts">
import { GitPullRequest, GitPullRequestDraft } from '@lucide/vue'
import type { BoardCard } from '@agent-dashboard/contracts'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import GateStrip from './GateStrip.vue'

defineProps<{ card: BoardCard }>()
</script>

<template>
  <Card class="gap-3 py-3">
    <CardHeader class="px-3">
      <CardTitle class="text-sm leading-snug">
        <a v-if="card.issue" :href="card.issue.url" target="_blank" rel="noopener noreferrer" class="hover:underline">
          #{{ card.issue.number }} {{ card.issue.title }}
        </a>
        <span v-else class="text-muted-foreground">No linked issue</span>
      </CardTitle>
      <CardDescription v-if="card.issue && card.issue.labels.length > 0" class="flex flex-wrap gap-1">
        <Badge v-for="label in card.issue.labels" :key="label.name" variant="secondary">{{ label.name }}</Badge>
      </CardDescription>
    </CardHeader>
    <CardContent v-if="card.pullRequest" class="flex flex-col gap-2 px-3">
      <a
        :href="card.pullRequest.url"
        target="_blank"
        rel="noopener noreferrer"
        class="flex items-center gap-1.5 text-xs hover:underline"
      >
        <GitPullRequestDraft v-if="card.pullRequest.isDraft" class="size-3.5" />
        <GitPullRequest v-else class="size-3.5" />
        #{{ card.pullRequest.number }} {{ card.pullRequest.title }}
      </a>
      <Badge v-if="card.pullRequest.mergeable === 'CONFLICTING'" variant="destructive">Merge conflict</Badge>
      <GateStrip :gates="card.pullRequest.gates" :summary="card.pullRequest.gateSummary" />
    </CardContent>
  </Card>
</template>

// apps/web/src/components/board/BoardCardItem.tsx
import { FileTextIcon, Link2Icon } from '@radix-ui/react-icons'
import { Badge, Card, Flex, Link, Separator, Text } from '@radix-ui/themes'
import type { BoardCard, RepositoryReference } from '@agent-dashboard/contracts'
import { GateStrip } from './GateStrip'
import { PullRequestActions } from './PullRequestActions'
import { PullRequestMedia } from './PullRequestMedia'

interface BoardCardItemProps {
  card: BoardCard
  repository: RepositoryReference
  onPullRequestChanged: () => void
}

/**
 * One board card: the issue, its labels, and its pull request with the check gates, the
 * screenshot and video, and the merge and close buttons.
 */
export const BoardCardItem = ({ card, repository, onPullRequestChanged }: BoardCardItemProps) => (
  <Card size="2">
    <Flex direction="column" gap="3">
      <Flex direction="column" gap="2">
        {card.issue ? (
          <Link href={card.issue.url} target="_blank" rel="noopener noreferrer" size="2" weight="medium" highContrast underline="hover">
            #{card.issue.number} {card.issue.title}
          </Link>
        ) : (
          <Text size="2" color="gray">
            No linked issue
          </Text>
        )}
        {card.issue && card.issue.labels.length > 0 && (
          <Flex gap="1" wrap="wrap">
            {card.issue.labels.map((label) => (
              <Badge key={label.name} variant="outline" color="gray" radius="full">
                {label.name}
              </Badge>
            ))}
          </Flex>
        )}
      </Flex>
      {card.pullRequest && (
        <>
          <Separator size="4" />
          <Flex direction="column" gap="2">
            <Flex gap="2" align="start">
              {card.pullRequest.isDraft ? <FileTextIcon /> : <Link2Icon />}
              <Link href={card.pullRequest.url} target="_blank" rel="noopener noreferrer" size="1" color="gray" underline="hover">
                #{card.pullRequest.number} {card.pullRequest.title}
              </Link>
            </Flex>
            {card.pullRequest.mergeable === 'CONFLICTING' && (
              <Badge color="red" radius="full">
                Merge conflict
              </Badge>
            )}
            <GateStrip gates={card.pullRequest.gates} summary={card.pullRequest.gateSummary} />
          </Flex>
          <Separator size="4" />
          <Flex justify="between" align="center" gap="3" wrap="wrap">
            <PullRequestMedia repository={repository} pullRequest={card.pullRequest} />
            <PullRequestActions repository={repository} pullRequest={card.pullRequest} onChanged={onPullRequestChanged} />
          </Flex>
        </>
      )}
    </Flex>
  </Card>
)
