// apps/web/src/components/credentials/SecretDialog.vue
<script setup lang="ts">
import { ref } from 'vue'
import { toast } from 'vue-sonner'
import type { SecretSummary } from '@agent-dashboard/contracts'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useVaultStore } from '@/stores/vault'

const props = defineProps<{ secret: SecretSummary; disabled: boolean }>()

const vaultStore = useVaultStore()
const isOpen = ref(false)
const secretValue = ref('')

const save = async (): Promise<void> => {
  try {
    await vaultStore.saveSecret(props.secret.name, secretValue.value)
    toast.success(`${props.secret.label} saved`)
    isOpen.value = false
  } catch (saveError) {
    toast.error(saveError instanceof Error ? saveError.message : 'The value could not be saved')
  } finally {
    secretValue.value = ''
  }
}
</script>

<template>
  <Dialog v-model:open="isOpen">
    <DialogTrigger as-child>
      <Button size="sm" :variant="secret.isSet ? 'outline' : 'default'" :disabled="disabled">
        {{ secret.isSet ? 'Replace' : 'Add' }}
      </Button>
    </DialogTrigger>
    <DialogContent>
      <form class="flex flex-col gap-4" @submit.prevent="save">
        <DialogHeader>
          <DialogTitle>{{ secret.label }}</DialogTitle>
          <DialogDescription>
            {{ secret.description }} The value is encrypted on the server and never shown again.
          </DialogDescription>
        </DialogHeader>
        <div class="flex flex-col gap-1.5">
          <Label :for="`secret-${secret.name}`">Value</Label>
          <Input :id="`secret-${secret.name}`" v-model="secretValue" type="password" autocomplete="off" spellcheck="false" />
        </div>
        <DialogFooter>
          <Button type="submit" :disabled="secretValue.trim().length === 0">Save</Button>
        </DialogFooter>
      </form>
    </DialogContent>
  </Dialog>
</template>

// apps/web/src/components/credentials/SecretDialog.tsx
import { Button, Dialog, Flex, Text, TextField } from '@radix-ui/themes'
import { useState, type FormEvent } from 'react'
import type { SecretSummary } from '@agent-dashboard/contracts'
import { useToast } from '@/hooks/useToast'

interface SecretDialogProps {
  secret: SecretSummary
  disabled: boolean
  onSave: (name: string, value: string) => Promise<void>
}

export const SecretDialog = ({ secret, disabled, onSave }: SecretDialogProps) => {
  const toast = useToast()
  const [isOpen, setIsOpen] = useState(false)
  const [secretValue, setSecretValue] = useState('')

  const save = async (submitEvent: FormEvent): Promise<void> => {
    submitEvent.preventDefault()
    try {
      await onSave(secret.name, secretValue)
      toast.notifySuccess(`${secret.label} saved`)
      setIsOpen(false)
    } catch (saveError) {
      toast.notifyError(saveError)
    } finally {
      setSecretValue('')
    }
  }

  return (
    <Dialog.Root open={isOpen} onOpenChange={setIsOpen}>
      <Dialog.Trigger>
        <Button size="1" variant={secret.isSet ? 'soft' : 'solid'} color={secret.isSet ? 'gray' : undefined} disabled={disabled}>
          {secret.isSet ? 'Replace' : 'Add'}
        </Button>
      </Dialog.Trigger>
      <Dialog.Content maxWidth="460px">
        <Dialog.Title>{secret.label}</Dialog.Title>
        <Dialog.Description size="2" color="gray" mb="4">
          {secret.description} The value is encrypted on the server and never shown again.
        </Dialog.Description>
        <form onSubmit={(submitEvent) => void save(submitEvent)}>
          <label>
            <Text as="div" size="2" mb="1" weight="medium">
              Value
            </Text>
            <TextField.Root
              type="password"
              autoComplete="off"
              spellCheck={false}
              autoFocus
              value={secretValue}
              onChange={(changeEvent) => setSecretValue(changeEvent.target.value)}
            />
          </label>
          <Flex gap="3" mt="5" justify="end">
            <Dialog.Close>
              <Button type="button" variant="soft" color="gray">
                Cancel
              </Button>
            </Dialog.Close>
            <Button type="submit" disabled={secretValue.trim().length === 0}>
              Save
            </Button>
          </Flex>
        </form>
      </Dialog.Content>
    </Dialog.Root>
  )
}
