// apps/web/src/components/credentials/VaultPanel.vue
<script setup lang="ts">
import { Lock, LockOpen } from '@lucide/vue'
import { ref } from 'vue'
import { toast } from 'vue-sonner'
import type { VaultState } from '@agent-dashboard/contracts'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useVaultStore } from '@/stores/vault'

defineProps<{ vaultState: VaultState }>()

const vaultStore = useVaultStore()
const passphrase = ref('')

const runWithToast = async (action: () => Promise<void>, successMessage: string): Promise<void> => {
  try {
    await action()
    passphrase.value = ''
    await vaultStore.refresh()
    toast.success(successMessage)
  } catch (actionError) {
    toast.error(actionError instanceof Error ? actionError.message : 'Something went wrong')
  }
}
</script>

<template>
  <Alert v-if="vaultState.mode === 'environment' && !vaultState.unlocked" variant="destructive">
    <Lock />
    <AlertTitle>The master key does not match</AlertTitle>
    <AlertDescription>
      The stored credentials were encrypted with a different AGENT_DASHBOARD_MASTER_KEY. Restart the dashboard with the
      original key.
    </AlertDescription>
  </Alert>

  <Alert v-else-if="vaultState.mode === 'environment'">
    <LockOpen />
    <AlertTitle>Unlocked by the master key</AlertTitle>
    <AlertDescription>Credentials are encrypted with the key from the environment.</AlertDescription>
  </Alert>

  <Alert v-else-if="vaultState.unlocked">
    <LockOpen />
    <AlertTitle>Unlocked until the next restart</AlertTitle>
    <AlertDescription class="flex flex-wrap items-center gap-2">
      The passphrase-derived key is held in memory only.
      <Button variant="outline" size="sm" @click="runWithToast(vaultStore.lock, 'Vault locked')">Lock now</Button>
    </AlertDescription>
  </Alert>

  <Alert v-else>
    <Lock />
    <AlertTitle>{{ vaultState.initialised ? 'The vault is locked' : 'Set a vault passphrase' }}</AlertTitle>
    <AlertDescription>
      <form
        class="mt-2 flex flex-wrap items-end gap-2"
        @submit.prevent="
          runWithToast(
            () => (vaultState.initialised ? vaultStore.unlock(passphrase) : vaultStore.setUp(passphrase)),
            vaultState.initialised ? 'Vault unlocked' : 'Vault created',
          )
        "
      >
        <div class="flex flex-col gap-1.5">
          <Label for="vault-passphrase">Passphrase</Label>
          <Input id="vault-passphrase" v-model="passphrase" type="password" autocomplete="current-password" class="w-72" />
        </div>
        <Button type="submit" :disabled="passphrase.length === 0">
          {{ vaultState.initialised ? 'Unlock' : 'Create vault' }}
        </Button>
      </form>
      <p v-if="!vaultState.initialised" class="mt-2 text-xs">
        At least 12 characters. It cannot be recovered: losing it means entering the credentials again.
      </p>
    </AlertDescription>
  </Alert>
</template>

// apps/web/src/components/credentials/VaultPanel.tsx
import { LockClosedIcon, LockOpen1Icon } from '@radix-ui/react-icons'
import { Button, Callout, Flex, Text, TextField } from '@radix-ui/themes'
import { useState, type FormEvent } from 'react'
import type { VaultState } from '@agent-dashboard/contracts'
import { useToast } from '@/hooks/useToast'

interface VaultPanelProps {
  vaultState: VaultState
  onSetUp: (passphrase: string) => Promise<void>
  onUnlock: (passphrase: string) => Promise<void>
  onLock: () => Promise<void>
}

export const VaultPanel = ({ vaultState, onSetUp, onUnlock, onLock }: VaultPanelProps) => {
  const toast = useToast()
  const [passphrase, setPassphrase] = useState('')

  const runVaultAction = async (action: () => Promise<void>, successMessage: string): Promise<void> => {
    try {
      await action()
      setPassphrase('')
      toast.notifySuccess(successMessage)
    } catch (actionError) {
      toast.notifyError(actionError)
    }
  }

  const submitPassphrase = (submitEvent: FormEvent): void => {
    submitEvent.preventDefault()
    void (vaultState.initialised
      ? runVaultAction(() => onUnlock(passphrase), 'Vault unlocked')
      : runVaultAction(() => onSetUp(passphrase), 'Vault created'))
  }

  if (vaultState.mode === 'environment') {
    return vaultState.unlocked ? (
      <Callout.Root color="green" variant="surface">
        <Callout.Icon>
          <LockOpen1Icon />
        </Callout.Icon>
        <Callout.Text>Unlocked by the master key from the environment.</Callout.Text>
      </Callout.Root>
    ) : (
      <Callout.Root color="red" variant="surface">
        <Callout.Icon>
          <LockClosedIcon />
        </Callout.Icon>
        <Callout.Text>
          The stored credentials were encrypted with a different AGENT_DASHBOARD_MASTER_KEY. Restart the dashboard with the
          original key.
        </Callout.Text>
      </Callout.Root>
    )
  }

  if (vaultState.unlocked) {
    return (
      <Callout.Root color="green" variant="surface">
        <Callout.Icon>
          <LockOpen1Icon />
        </Callout.Icon>
        <Flex justify="between" align="center" gap="3" wrap="wrap">
          <Callout.Text>Unlocked until the next restart. The passphrase-derived key is held in memory only.</Callout.Text>
          <Button size="1" variant="soft" color="gray" onClick={() => void runVaultAction(onLock, 'Vault locked')}>
            Lock now
          </Button>
        </Flex>
      </Callout.Root>
    )
  }

  return (
    <Callout.Root variant="surface">
      <Callout.Icon>
        <LockClosedIcon />
      </Callout.Icon>
      <Flex direction="column" gap="3">
        <Text size="2" weight="medium">
          {vaultState.initialised ? 'The vault is locked' : 'Set a vault passphrase'}
        </Text>
        <form onSubmit={submitPassphrase}>
          <Flex gap="2" wrap="wrap" align="center">
            <TextField.Root
              type="password"
              placeholder="Passphrase"
              aria-label="Passphrase"
              autoComplete="current-password"
              value={passphrase}
              onChange={(changeEvent) => setPassphrase(changeEvent.target.value)}
              style={{ minWidth: 260 }}
            />
            <Button type="submit" disabled={passphrase.length === 0}>
              {vaultState.initialised ? 'Unlock' : 'Create vault'}
            </Button>
          </Flex>
        </form>
        {!vaultState.initialised && (
          <Text size="1" color="gray">
            At least 12 characters. It cannot be recovered: losing it means entering the credentials again.
          </Text>
        )}
      </Flex>
    </Callout.Root>
  )
}
